In [2]:
import numpy as np
list_ = [ "1" , "2" , "3" , "4" , "5" ]
array_list = np.array(object = list_)

### Question 1.

In [6]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


here first is list which is data structure of python. And second one is ndarray which is part of numpy and it means n dimention array.

### Question 2.

In [10]:
print("types in list_")
for element in list_:
    print(type(element))
print()
    
print("types in array_list")
for element in array_list:
    print(type(element))    

types in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

types in array_list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Question 3.

In [11]:
array_list = np.array(object = list_, dtype = int)
print(type(array_list))

array([1, 2, 3, 4, 5])

by adding dtype it will change string into int

In [12]:
print("types in list_")
for element in list_:
    print(type(element))
print()
    
print("types in array_list")
for element in array_list:
    print(type(element))   

types in list_
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

types in array_list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Question 4.

In [13]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [18]:
print("shape: ", num_array.shape)
print("size: ", num_array.size)


shape:  (2, 3)
size:  6


### Question 5.

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Question 6.

In [25]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])